export const FIND_CATEGORY_LIST = 'category/FIND_CATEGORY_LIST';
export const SET_CATEGORY_LIST_ASYNC = 'category/SET_CATEGORY_LIST_ASYNC';

export const FIND_CATEGORY = 'category/FIND_CATEGORY';

export const UPDATE_CATEGORY_REQUEST = 'category/UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY = 'category/UPDATE_CATEGORY';

export const SAVE_CATEGORY_REQUEST = 'category/SAVE_CATEGORY_REQUEST';
export const SAVE_CATEGORY = 'category/SAVE_CATEGORY';

export const REMOVE_CATEGORY_REQUEST = 'category/REMOVE_CATEGORY_REQUEST';
export const REMOVE_CATEGORY = 'category/REMOVE_CATEGORY';