export const FIND_CATEGORY_LIST = 'category/FIND_CATEGORY_LIST';
export const FIND_CATEGORY_LIST_REQUEST = 'category/FIND_CATEGORY_LIST_REQUEST';
export const FIND_CATEGORY_LIST_SUCCESS = 'category/FIND_CATEGORY_LIST_SUCCESS';
export const FIND_CATEGORY_LIST_FAILURE = 'category/FIND_CATEGORY_LIST_FAILURE';

export const FIND_CATEGORY = 'category/FIND_CATEGORY';

export const UPDATE_CATEGORY = 'category/UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'category/UPDATE_CATEGORY_SUCCESS';

export const SAVE_CATEGORY = 'category/SAVE_CATEGORY';
export const SAVE_CATEGORY_SUCCESS = 'category/SAVE_CATEGORY_SUCCESS';

export const REMOVE_CATEGORY = 'category/REMOVE_CATEGORY';
export const REMOVE_CATEGORY_SUCCESS = 'category/REMOVE_CATEGORY_SUCCESS';