export const FIND_POINT_HISTORY_PAGE = 'pointHistory/FIND_POINT_HISTORY_PAGE';
export const FIND_POINT_HISTORY_PAGE_REQUEST = 'pointHistory/FIND_POINT_HISTORY_PAGE_REQUEST';
export const FIND_POINT_HISTORY_PAGE_SUCCESS = 'pointHistory/FIND_POINT_HISTORY_PAGE_SUCCESS';
export const FIND_POINT_HISTORY_PAGE_FAILURE = 'pointHistory/FIND_POINT_HISTORY_PAGE_FAILURE';