export const FIND_DISCOUNT_POLICY_LIST = 'discountPolicy/FIND_DISCOUNT_POLICY_LIST';
export const SET_DISCOUNT_POLICY_LIST_ASYNC = 'discountPolicy/SET_DISCOUNT_POLICY_LIST_ASYNC';

export const FIND_DISCOUNT_POLICY = 'discountPolicy/FIND_DISCOUNT_POLICY';

export const UPDATE_DISCOUNT_POLICY_REQUEST = 'discountPolicy/UPDATE_DISCOUNT_POLICY_REQUEST';
export const UPDATE_DISCOUNT_POLICY = 'discountPolicy/UPDATE_DISCOUNT_POLICY';

export const SAVE_DISCOUNT_POLICY_REQUEST = 'discountPolicy/SAVE_DISCOUNT_POLICY_REQUEST';
export const SAVE_DISCOUNT_POLICY = 'discountPolicy/SAVE_DISCOUNT_POLICY';