export const FIND_DISCOUNT_POLICY_LIST = 'discountPolicy/FIND_DISCOUNT_POLICY_LIST';
export const FIND_DISCOUNT_POLICY_LIST_REQUEST = 'discountPolicy/FIND_DISCOUNT_POLICY_LIST_REQUEST';
export const FIND_DISCOUNT_POLICY_LIST_SUCCESS = 'discountPolicy/FIND_DISCOUNT_POLICY_LIST_SUCCESS';
export const FIND_DISCOUNT_POLICY_LIST_FAILURE = 'discountPolicy/FIND_DISCOUNT_POLICY_LIST_FAILURE';

export const FIND_DISCOUNT_POLICY = 'discountPolicy/FIND_DISCOUNT_POLICY';

export const UPDATE_DISCOUNT_POLICY = 'discountPolicy/UPDATE_DISCOUNT_POLICY';
export const UPDATE_DISCOUNT_POLICY_SUCCESS = 'discountPolicy/UPDATE_DISCOUNT_POLICY_SUCCESS';

export const SAVE_DISCOUNT_POLICY = 'discountPolicy/SAVE_DISCOUNT_POLICY';
export const SAVE_DISCOUNT_POLICY_SUCCESS = 'discountPolicy/SAVE_DISCOUNT_POLICY_SUCCESS';