export const FIND_PRODUCT_PAGE = 'product/FIND_PRODUCT_PAGE';
export const FIND_PRODUCT_PAGE_REQUEST = 'product/FIND_PRODUCT_PAGE_REQUEST';
export const FIND_PRODUCT_PAGE_SUCCESS = 'product/FIND_PRODUCT_PAGE_SUCCESS';
export const FIND_PRODUCT_PAGE_FAILURE = 'product/FIND_PRODUCT_PAGE_FAILURE';

export const FIND_PRODUCT = 'product/FIND_PRODUCT';
export const FIND_PRODUCT_REQUEST = 'product/FIND_PRODUCT_REQUEST';
export const FIND_PRODUCT_SUCCESS = 'product/FIND_PRODUCT_SUCCESS';
export const FIND_PRODUCT_FAILURE = 'product/FIND_PRODUCT_FAILURE';

export const UPDATE_PRODUCT = 'product/UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'product/UPDATE_PRODUCT_SUCCESS';

export const SAVE_PRODUCT = 'product/SAVE_PRODUCT';
export const SAVE_PRODUCT_SUCCESS = 'product/SAVE_PRODUCT_SUCCESS';